// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWebsite(arg1, arg2) {
  return window['go']['main']['App']['AddWebsite'](arg1, arg2);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function DeleteWebsite(arg1) {
  return window['go']['main']['App']['DeleteWebsite'](arg1);
}

export function GetAllWebsites() {
  return window['go']['main']['App']['GetAllWebsites']();
}

export function GoBackHome() {
  return window['go']['main']['App']['GoBackHome']();
}

export function NavigateToWebsite(arg1) {
  return window['go']['main']['App']['NavigateToWebsite'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}
