// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddWebsite(arg1:string,arg2:string):Promise<void>;

export function Close():Promise<void>;

export function DeleteWebsite(arg1:number):Promise<void>;

export function GetAllWebsites():Promise<Array<main.Website>>;

export function GoBackHome():Promise<void>;

export function NavigateToWebsite(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;
